### PR TITLE
Fixes #299

### LINKED ISSUE #299: doesBucketExistV2 crashes when bucket doesnot exist on windows
`Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: java.nio.file.NoSuchFileException: \tmp\s3proxy\test1 (Service: Amazon S3; Status Code: 500; Error Code: 500 java.nio.file.NoSuchFileException: \tmp\s3proxy\test1; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4319)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4266)
	at com.amazonaws.services.s3.AmazonS3Client.getAcl(AmazonS3Client.java:3471)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1168)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1158)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExistV2(AmazonS3Client.java:1293)`

### PR DESCRIPTION
**Pull request by kerkhofsd**
Fixes #299 

Issue:
1. `AmazonS3Client#doesBucketExistV2(String bucketName)`
2. internally uses `AmazonS3Client#getBucketAcl(String bucketName)`
3. The `S3ProxyHandler` thew an exception on a GET Bucket ACL request for buckets that do not exist. 

Fixed it by making sure the `S3ProxyHandler` GET Bucket ACL correctly responds with a 404 if the bucket does not exist.

### CODE REVIEW

File: src/main/java/org/gaul/s3proxy/S3ProxyHandler.java [hunk 1]
```diff
@@ -844,8 +844,11 @@ private void doHandleAnonymous(HttpServletRequest request,
     }
 
     private void handleGetContainerAcl(HttpServletResponse response,
-            BlobStore blobStore, String containerName) throws IOException {
-        ContainerAccess access = blobStore.getContainerAccess(containerName);
+            BlobStore blobStore, String containerName)
+            throws IOException, S3Exception {
+        if (!blobStore.containerExists(containerName)) {
+            throw new S3Exception(S3ErrorCode.NO_SUCH_BUCKET);
+        }
```
Comment (gaul) [inline src/main/java/org/gaul/s3proxy/S3ProxyHandler.java]: Can you add back the `getContainerAccess` call below the `containerExists`?  This minimizes the diff and avoids possible exceptions while writing the response to the client.

**Comment by gaul** [comment]
Thank you for your contribution @kerkhofsd!
